version: '3.8'

services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: scanner
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - mynetwork
    restart:
      - always

  web:
    build: .
    command: gunicorn app_report.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2 --timeout 420
    volumes:
      - ./static:/app/static
      - ./outputs:/app/outputs
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=scanner
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=password
    networks:
      - mynetwork
    restart:
      - always
      
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork
    restart:
      -always
      
networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
  static:
