# Generated by Django 5.0.3 on 2025-01-30 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputfiles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
