# Generated by Django 5.1.5 on 2025-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
