# Generated by Django 5.1.4 on 2025-02-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_outputfiles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputfiles',
            name='md5check',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
