# Generated by Django 5.1.4 on 2025-02-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_outputfiles_md5check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputfiles',
            name='md5check',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
